### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by laurentlourenco** [spacelephant/spacelephant.github.io#34]
* Cosmetic
- [x] Change the footer info about the company: Incorporated # 839193422 RCS Nantes, France
- [x] remove Laure's profil
- [x] add twitter and medium account icons/links at the top right : https://medium.com/spacelephant https://twitter.com/spacelephant01
- [x] change Robin's name : Robin Lacombe-Delpech
- [x] in the product section, activate the 2 products UNS & SonarPlanet (PR #33) 
- [x] duplicate social media icons and links in the footer : right
- [x] add a link to sonarplanet in products section

**Comment by Nigui** [comment]
What does last item means ?! It seems that no media icons are currently in footer.

**Comment by Nigui** [comment]
penultimate item is for @ftreguer. He is the reviewer. He must merge the PR #33

**Comment by ftreguer** [comment]
Merged.
