### ISSUE TITLE
Strange icons positioning in Safari

### ISSUE THREAD

**Issue by Nigui** [spacelephant/spacelephant.github.io#39]
In Safari browser, media icons are not well positioned. See : 

<img width="436" alt="capture d ecran 2018-05-15 a 23 07 40" src="https://user-images.githubusercontent.com/6088236/40083631-15d8dc4e-5895-11e8-9995-2d77091af0b4.png">
<img width="829" alt="capture d ecran 2018-05-15 a 23 07 49" src="https://user-images.githubusercontent.com/6088236/40083632-15f5c0d4-5895-11e8-8f20-f25363ff7a36.png">

**Comment by ftreguer** [comment]
Fixed by #50
